// flow-typed signature: df6c9c5076f71875ffe9b20c2ca89f14
// flow-typed version: <<STUB>>/expo-status-bar_v^1.0.2/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-status-bar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-status-bar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-status-bar/build/ExpoStatusBar.android' {
  declare module.exports: any;
}

declare module 'expo-status-bar/build/ExpoStatusBar.ios' {
  declare module.exports: any;
}

declare module 'expo-status-bar/build/ExpoStatusBar' {
  declare module.exports: any;
}

declare module 'expo-status-bar/build/setStatusBarBackgroundColor' {
  declare module.exports: any;
}

declare module 'expo-status-bar/build/setStatusBarHidden' {
  declare module.exports: any;
}

declare module 'expo-status-bar/build/setStatusBarNetworkActivityIndicatorVisible' {
  declare module.exports: any;
}

declare module 'expo-status-bar/build/setStatusBarStyle' {
  declare module.exports: any;
}

declare module 'expo-status-bar/build/setStatusBarTranslucent' {
  declare module.exports: any;
}

declare module 'expo-status-bar/build/StatusBar' {
  declare module.exports: any;
}

declare module 'expo-status-bar/build/StatusBar.types' {
  declare module.exports: any;
}

declare module 'expo-status-bar/build/styleToBarStyle' {
  declare module.exports: any;
}

declare module 'expo-status-bar/build/styleToBarStyle.web' {
  declare module.exports: any;
}

declare module 'expo-status-bar/build/useColorScheme' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-status-bar/build/ExpoStatusBar.android.js' {
  declare module.exports: $Exports<'expo-status-bar/build/ExpoStatusBar.android'>;
}
declare module 'expo-status-bar/build/ExpoStatusBar.ios.js' {
  declare module.exports: $Exports<'expo-status-bar/build/ExpoStatusBar.ios'>;
}
declare module 'expo-status-bar/build/ExpoStatusBar.js' {
  declare module.exports: $Exports<'expo-status-bar/build/ExpoStatusBar'>;
}
declare module 'expo-status-bar/build/setStatusBarBackgroundColor.js' {
  declare module.exports: $Exports<'expo-status-bar/build/setStatusBarBackgroundColor'>;
}
declare module 'expo-status-bar/build/setStatusBarHidden.js' {
  declare module.exports: $Exports<'expo-status-bar/build/setStatusBarHidden'>;
}
declare module 'expo-status-bar/build/setStatusBarNetworkActivityIndicatorVisible.js' {
  declare module.exports: $Exports<'expo-status-bar/build/setStatusBarNetworkActivityIndicatorVisible'>;
}
declare module 'expo-status-bar/build/setStatusBarStyle.js' {
  declare module.exports: $Exports<'expo-status-bar/build/setStatusBarStyle'>;
}
declare module 'expo-status-bar/build/setStatusBarTranslucent.js' {
  declare module.exports: $Exports<'expo-status-bar/build/setStatusBarTranslucent'>;
}
declare module 'expo-status-bar/build/StatusBar.js' {
  declare module.exports: $Exports<'expo-status-bar/build/StatusBar'>;
}
declare module 'expo-status-bar/build/StatusBar.types.js' {
  declare module.exports: $Exports<'expo-status-bar/build/StatusBar.types'>;
}
declare module 'expo-status-bar/build/styleToBarStyle.js' {
  declare module.exports: $Exports<'expo-status-bar/build/styleToBarStyle'>;
}
declare module 'expo-status-bar/build/styleToBarStyle.web.js' {
  declare module.exports: $Exports<'expo-status-bar/build/styleToBarStyle.web'>;
}
declare module 'expo-status-bar/build/useColorScheme.js' {
  declare module.exports: $Exports<'expo-status-bar/build/useColorScheme'>;
}
