// flow-typed signature: 3af52c9b586c9b1267bbc5ca3e0c969b
// flow-typed version: <<STUB>>/@ui-kitten/components_v^5.0.0/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ui-kitten/components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ui-kitten/components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ui-kitten/components/devsupport/components/falsyFC/falsyFC.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/devsupport/components/falsyText/falsyText.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/devsupport/components/measure/measure.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/devsupport/components/measure/type' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/devsupport/components/touchableWeb.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/devsupport/components/touchableWithoutFeedback.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/devsupport' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/devsupport/services/props/props.service' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/devsupport/services/rtl/rtl.service' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/devsupport/services/rtl/rtlFlexMap' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/devsupport/services/web/webEventResponder' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/devsupport/typings' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/theme/application/applicationProvider.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/theme' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/theme/mapping/mappingContext' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/theme/mapping/mappingProvider.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/theme/modal/modal.service' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/theme/modal/modalPanel.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/theme/modal/modalResolver.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/theme/style/style.service' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/theme/style/styleConsumer.service' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/theme/style/styled' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/theme/style/styleProvider.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/theme/theme/theme.service' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/theme/theme/themeContext' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/theme/theme/themeProvider.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/theme/theme/withStyles' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/animation/animation' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/animation' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/animation/pulseAnimation' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/animation/shakeAnimation' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/animation/zoomAnimation' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/autocomplete/autocomplete.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/autocomplete/autocompleteItem.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/avatar/avatar.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/bottomNavigation/bottomNavigation.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/bottomNavigation/bottomNavigationTab.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/button/button.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/buttonGroup/buttonGroup.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/calendar/baseCalendar.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/calendar/calendar.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/calendar/components/calendarDateContent.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/calendar/components/calendarHeader.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/calendar/components/calendarMonthHeader.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/calendar/components/picker/calendarPicker.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/calendar/components/picker/calendarPickerCell.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/calendar/components/picker/calendarPickerRow.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/calendar/i18n/en' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/calendar/i18n/type' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/calendar/rangeCalendar.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/calendar/service/calendarData.service' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/calendar/service/date.service' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/calendar/service/helpers' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/calendar/service/nativeDate.service' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/calendar/service/rangeDate.service' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/calendar/type' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/card/card.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/checkbox/checkbox.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/datepicker/baseDatepicker.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/datepicker/datepicker.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/datepicker/rangeDatepicker.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/divider/divider.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/drawer/drawer.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/drawer/drawerGroup.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/drawer/drawerItem.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/icon/icon.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/icon/iconAnimation' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/icon/iconRegistry.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/icon/service/iconRegistry.service' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/icon/service/type' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/input/input.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/layout/layout.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/list/list.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/list/listItem.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/menu/menu.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/menu/menu.service' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/menu/menuGroup.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/menu/menuItem.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/modal/modal.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/overflowMenu/overflowMenu.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/popover/placement.service' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/popover/popover.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/popover/popoverIndicator.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/popover/popoverView.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/popover/type' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/radio/radio.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/radioGroup/radioGroup.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/select/select.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/select/select.service' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/select/selectGroup.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/select/selectItem.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/shared/checkmark.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/shared/chevronDown.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/shared/chevronLeft.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/shared/chevronRight.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/shared/minus.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/shared/tabIndicator.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/spinner/animation' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/spinner/spinner.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/tab/tab.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/tab/tabBar.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/tab/tabView.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/text/text.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/toggle/toggle.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/tooltip/tooltip.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/topNavigation/topNavigation.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/topNavigation/topNavigationAction.component' {
  declare module.exports: any;
}

declare module '@ui-kitten/components/ui/viewPager/viewPager.component' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ui-kitten/components/devsupport/components/falsyFC/falsyFC.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/devsupport/components/falsyFC/falsyFC.component'>;
}
declare module '@ui-kitten/components/devsupport/components/falsyText/falsyText.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/devsupport/components/falsyText/falsyText.component'>;
}
declare module '@ui-kitten/components/devsupport/components/measure/measure.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/devsupport/components/measure/measure.component'>;
}
declare module '@ui-kitten/components/devsupport/components/measure/type.js' {
  declare module.exports: $Exports<'@ui-kitten/components/devsupport/components/measure/type'>;
}
declare module '@ui-kitten/components/devsupport/components/touchableWeb.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/devsupport/components/touchableWeb.component'>;
}
declare module '@ui-kitten/components/devsupport/components/touchableWithoutFeedback.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/devsupport/components/touchableWithoutFeedback.component'>;
}
declare module '@ui-kitten/components/devsupport/index' {
  declare module.exports: $Exports<'@ui-kitten/components/devsupport'>;
}
declare module '@ui-kitten/components/devsupport/index.js' {
  declare module.exports: $Exports<'@ui-kitten/components/devsupport'>;
}
declare module '@ui-kitten/components/devsupport/services/props/props.service.js' {
  declare module.exports: $Exports<'@ui-kitten/components/devsupport/services/props/props.service'>;
}
declare module '@ui-kitten/components/devsupport/services/rtl/rtl.service.js' {
  declare module.exports: $Exports<'@ui-kitten/components/devsupport/services/rtl/rtl.service'>;
}
declare module '@ui-kitten/components/devsupport/services/rtl/rtlFlexMap.js' {
  declare module.exports: $Exports<'@ui-kitten/components/devsupport/services/rtl/rtlFlexMap'>;
}
declare module '@ui-kitten/components/devsupport/services/web/webEventResponder.js' {
  declare module.exports: $Exports<'@ui-kitten/components/devsupport/services/web/webEventResponder'>;
}
declare module '@ui-kitten/components/devsupport/typings.js' {
  declare module.exports: $Exports<'@ui-kitten/components/devsupport/typings'>;
}
declare module '@ui-kitten/components/index' {
  declare module.exports: $Exports<'@ui-kitten/components'>;
}
declare module '@ui-kitten/components/index.js' {
  declare module.exports: $Exports<'@ui-kitten/components'>;
}
declare module '@ui-kitten/components/theme/application/applicationProvider.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/theme/application/applicationProvider.component'>;
}
declare module '@ui-kitten/components/theme/index' {
  declare module.exports: $Exports<'@ui-kitten/components/theme'>;
}
declare module '@ui-kitten/components/theme/index.js' {
  declare module.exports: $Exports<'@ui-kitten/components/theme'>;
}
declare module '@ui-kitten/components/theme/mapping/mappingContext.js' {
  declare module.exports: $Exports<'@ui-kitten/components/theme/mapping/mappingContext'>;
}
declare module '@ui-kitten/components/theme/mapping/mappingProvider.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/theme/mapping/mappingProvider.component'>;
}
declare module '@ui-kitten/components/theme/modal/modal.service.js' {
  declare module.exports: $Exports<'@ui-kitten/components/theme/modal/modal.service'>;
}
declare module '@ui-kitten/components/theme/modal/modalPanel.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/theme/modal/modalPanel.component'>;
}
declare module '@ui-kitten/components/theme/modal/modalResolver.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/theme/modal/modalResolver.component'>;
}
declare module '@ui-kitten/components/theme/style/style.service.js' {
  declare module.exports: $Exports<'@ui-kitten/components/theme/style/style.service'>;
}
declare module '@ui-kitten/components/theme/style/styleConsumer.service.js' {
  declare module.exports: $Exports<'@ui-kitten/components/theme/style/styleConsumer.service'>;
}
declare module '@ui-kitten/components/theme/style/styled.js' {
  declare module.exports: $Exports<'@ui-kitten/components/theme/style/styled'>;
}
declare module '@ui-kitten/components/theme/style/styleProvider.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/theme/style/styleProvider.component'>;
}
declare module '@ui-kitten/components/theme/theme/theme.service.js' {
  declare module.exports: $Exports<'@ui-kitten/components/theme/theme/theme.service'>;
}
declare module '@ui-kitten/components/theme/theme/themeContext.js' {
  declare module.exports: $Exports<'@ui-kitten/components/theme/theme/themeContext'>;
}
declare module '@ui-kitten/components/theme/theme/themeProvider.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/theme/theme/themeProvider.component'>;
}
declare module '@ui-kitten/components/theme/theme/withStyles.js' {
  declare module.exports: $Exports<'@ui-kitten/components/theme/theme/withStyles'>;
}
declare module '@ui-kitten/components/ui/animation/animation.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/animation/animation'>;
}
declare module '@ui-kitten/components/ui/animation/index' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/animation'>;
}
declare module '@ui-kitten/components/ui/animation/index.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/animation'>;
}
declare module '@ui-kitten/components/ui/animation/pulseAnimation.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/animation/pulseAnimation'>;
}
declare module '@ui-kitten/components/ui/animation/shakeAnimation.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/animation/shakeAnimation'>;
}
declare module '@ui-kitten/components/ui/animation/zoomAnimation.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/animation/zoomAnimation'>;
}
declare module '@ui-kitten/components/ui/autocomplete/autocomplete.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/autocomplete/autocomplete.component'>;
}
declare module '@ui-kitten/components/ui/autocomplete/autocompleteItem.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/autocomplete/autocompleteItem.component'>;
}
declare module '@ui-kitten/components/ui/avatar/avatar.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/avatar/avatar.component'>;
}
declare module '@ui-kitten/components/ui/bottomNavigation/bottomNavigation.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/bottomNavigation/bottomNavigation.component'>;
}
declare module '@ui-kitten/components/ui/bottomNavigation/bottomNavigationTab.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/bottomNavigation/bottomNavigationTab.component'>;
}
declare module '@ui-kitten/components/ui/button/button.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/button/button.component'>;
}
declare module '@ui-kitten/components/ui/buttonGroup/buttonGroup.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/buttonGroup/buttonGroup.component'>;
}
declare module '@ui-kitten/components/ui/calendar/baseCalendar.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/calendar/baseCalendar.component'>;
}
declare module '@ui-kitten/components/ui/calendar/calendar.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/calendar/calendar.component'>;
}
declare module '@ui-kitten/components/ui/calendar/components/calendarDateContent.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/calendar/components/calendarDateContent.component'>;
}
declare module '@ui-kitten/components/ui/calendar/components/calendarHeader.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/calendar/components/calendarHeader.component'>;
}
declare module '@ui-kitten/components/ui/calendar/components/calendarMonthHeader.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/calendar/components/calendarMonthHeader.component'>;
}
declare module '@ui-kitten/components/ui/calendar/components/picker/calendarPicker.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/calendar/components/picker/calendarPicker.component'>;
}
declare module '@ui-kitten/components/ui/calendar/components/picker/calendarPickerCell.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/calendar/components/picker/calendarPickerCell.component'>;
}
declare module '@ui-kitten/components/ui/calendar/components/picker/calendarPickerRow.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/calendar/components/picker/calendarPickerRow.component'>;
}
declare module '@ui-kitten/components/ui/calendar/i18n/en.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/calendar/i18n/en'>;
}
declare module '@ui-kitten/components/ui/calendar/i18n/type.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/calendar/i18n/type'>;
}
declare module '@ui-kitten/components/ui/calendar/rangeCalendar.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/calendar/rangeCalendar.component'>;
}
declare module '@ui-kitten/components/ui/calendar/service/calendarData.service.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/calendar/service/calendarData.service'>;
}
declare module '@ui-kitten/components/ui/calendar/service/date.service.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/calendar/service/date.service'>;
}
declare module '@ui-kitten/components/ui/calendar/service/helpers.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/calendar/service/helpers'>;
}
declare module '@ui-kitten/components/ui/calendar/service/nativeDate.service.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/calendar/service/nativeDate.service'>;
}
declare module '@ui-kitten/components/ui/calendar/service/rangeDate.service.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/calendar/service/rangeDate.service'>;
}
declare module '@ui-kitten/components/ui/calendar/type.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/calendar/type'>;
}
declare module '@ui-kitten/components/ui/card/card.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/card/card.component'>;
}
declare module '@ui-kitten/components/ui/checkbox/checkbox.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/checkbox/checkbox.component'>;
}
declare module '@ui-kitten/components/ui/datepicker/baseDatepicker.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/datepicker/baseDatepicker.component'>;
}
declare module '@ui-kitten/components/ui/datepicker/datepicker.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/datepicker/datepicker.component'>;
}
declare module '@ui-kitten/components/ui/datepicker/rangeDatepicker.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/datepicker/rangeDatepicker.component'>;
}
declare module '@ui-kitten/components/ui/divider/divider.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/divider/divider.component'>;
}
declare module '@ui-kitten/components/ui/drawer/drawer.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/drawer/drawer.component'>;
}
declare module '@ui-kitten/components/ui/drawer/drawerGroup.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/drawer/drawerGroup.component'>;
}
declare module '@ui-kitten/components/ui/drawer/drawerItem.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/drawer/drawerItem.component'>;
}
declare module '@ui-kitten/components/ui/icon/icon.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/icon/icon.component'>;
}
declare module '@ui-kitten/components/ui/icon/iconAnimation.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/icon/iconAnimation'>;
}
declare module '@ui-kitten/components/ui/icon/iconRegistry.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/icon/iconRegistry.component'>;
}
declare module '@ui-kitten/components/ui/icon/service/iconRegistry.service.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/icon/service/iconRegistry.service'>;
}
declare module '@ui-kitten/components/ui/icon/service/type.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/icon/service/type'>;
}
declare module '@ui-kitten/components/ui/index' {
  declare module.exports: $Exports<'@ui-kitten/components/ui'>;
}
declare module '@ui-kitten/components/ui/index.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui'>;
}
declare module '@ui-kitten/components/ui/input/input.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/input/input.component'>;
}
declare module '@ui-kitten/components/ui/layout/layout.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/layout/layout.component'>;
}
declare module '@ui-kitten/components/ui/list/list.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/list/list.component'>;
}
declare module '@ui-kitten/components/ui/list/listItem.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/list/listItem.component'>;
}
declare module '@ui-kitten/components/ui/menu/menu.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/menu/menu.component'>;
}
declare module '@ui-kitten/components/ui/menu/menu.service.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/menu/menu.service'>;
}
declare module '@ui-kitten/components/ui/menu/menuGroup.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/menu/menuGroup.component'>;
}
declare module '@ui-kitten/components/ui/menu/menuItem.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/menu/menuItem.component'>;
}
declare module '@ui-kitten/components/ui/modal/modal.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/modal/modal.component'>;
}
declare module '@ui-kitten/components/ui/overflowMenu/overflowMenu.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/overflowMenu/overflowMenu.component'>;
}
declare module '@ui-kitten/components/ui/popover/placement.service.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/popover/placement.service'>;
}
declare module '@ui-kitten/components/ui/popover/popover.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/popover/popover.component'>;
}
declare module '@ui-kitten/components/ui/popover/popoverIndicator.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/popover/popoverIndicator.component'>;
}
declare module '@ui-kitten/components/ui/popover/popoverView.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/popover/popoverView.component'>;
}
declare module '@ui-kitten/components/ui/popover/type.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/popover/type'>;
}
declare module '@ui-kitten/components/ui/radio/radio.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/radio/radio.component'>;
}
declare module '@ui-kitten/components/ui/radioGroup/radioGroup.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/radioGroup/radioGroup.component'>;
}
declare module '@ui-kitten/components/ui/select/select.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/select/select.component'>;
}
declare module '@ui-kitten/components/ui/select/select.service.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/select/select.service'>;
}
declare module '@ui-kitten/components/ui/select/selectGroup.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/select/selectGroup.component'>;
}
declare module '@ui-kitten/components/ui/select/selectItem.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/select/selectItem.component'>;
}
declare module '@ui-kitten/components/ui/shared/checkmark.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/shared/checkmark.component'>;
}
declare module '@ui-kitten/components/ui/shared/chevronDown.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/shared/chevronDown.component'>;
}
declare module '@ui-kitten/components/ui/shared/chevronLeft.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/shared/chevronLeft.component'>;
}
declare module '@ui-kitten/components/ui/shared/chevronRight.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/shared/chevronRight.component'>;
}
declare module '@ui-kitten/components/ui/shared/minus.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/shared/minus.component'>;
}
declare module '@ui-kitten/components/ui/shared/tabIndicator.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/shared/tabIndicator.component'>;
}
declare module '@ui-kitten/components/ui/spinner/animation.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/spinner/animation'>;
}
declare module '@ui-kitten/components/ui/spinner/spinner.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/spinner/spinner.component'>;
}
declare module '@ui-kitten/components/ui/tab/tab.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/tab/tab.component'>;
}
declare module '@ui-kitten/components/ui/tab/tabBar.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/tab/tabBar.component'>;
}
declare module '@ui-kitten/components/ui/tab/tabView.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/tab/tabView.component'>;
}
declare module '@ui-kitten/components/ui/text/text.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/text/text.component'>;
}
declare module '@ui-kitten/components/ui/toggle/toggle.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/toggle/toggle.component'>;
}
declare module '@ui-kitten/components/ui/tooltip/tooltip.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/tooltip/tooltip.component'>;
}
declare module '@ui-kitten/components/ui/topNavigation/topNavigation.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/topNavigation/topNavigation.component'>;
}
declare module '@ui-kitten/components/ui/topNavigation/topNavigationAction.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/topNavigation/topNavigationAction.component'>;
}
declare module '@ui-kitten/components/ui/viewPager/viewPager.component.js' {
  declare module.exports: $Exports<'@ui-kitten/components/ui/viewPager/viewPager.component'>;
}
