// flow-typed signature: 7d4934e441a7272f318d7b6389739204
// flow-typed version: <<STUB>>/@ui-kitten/eva-icons_v^5.0.0/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ui-kitten/eva-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ui-kitten/eva-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ui-kitten/eva-icons/createIconsMap' {
  declare module.exports: any;
}

declare module '@ui-kitten/eva-icons/evaIcon.component' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ui-kitten/eva-icons/createIconsMap.js' {
  declare module.exports: $Exports<'@ui-kitten/eva-icons/createIconsMap'>;
}
declare module '@ui-kitten/eva-icons/evaIcon.component.js' {
  declare module.exports: $Exports<'@ui-kitten/eva-icons/evaIcon.component'>;
}
declare module '@ui-kitten/eva-icons/index' {
  declare module.exports: $Exports<'@ui-kitten/eva-icons'>;
}
declare module '@ui-kitten/eva-icons/index.js' {
  declare module.exports: $Exports<'@ui-kitten/eva-icons'>;
}
